project:
  type: website

website:
  title: "Carolynn Rui"
  navbar:
    right:
      - href: index.qmd
        text: Overview
      - href: about.qmd
        text: Who I Am
      - href: projects.qmd
        text: Projects
      - href: onstage_highlights.qmd
        text: Onstage

format:
  html:
    theme: quartz
    css: styles.css
    toc: true

editor: visual

execute:
  freeze: auto

